### ISSUE TITLE
Nightly releases are failing

### ISSUE THREAD

**Issue by dsimansk** [knative-sandbox/kn-plugin-event#100]
That might be related to `v1.0.0` release

```
[MAGE] ✅ Testing was successful.
[MAGE] 🔨 Building
[MAGE] 🔨 › 💿 kn-event-sender
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Error: unexpected error: running "git ls-remote --tags origin" failed with exit code 128
exit status 1
+ EXIT_VALUE=1
+ set +o xtrace 
```

See the log:
https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-kn-plugin-event-nightly-release/1457996516202385408#1:build-log.txt%3A1186

**Comment by cardil** [comment]
Thanks for raising this @dsimansk!

I rather think this is connected to merge of #87. For whatever reason, the `origin` isn't set there.

Luckily, we could easily set that. PR comming...

/assign
