### ISSUE TITLE
Repository should be consistent with all other Knative repos

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/kn-plugin-event#13]
As per title, to make it fit seamlessly into workflows. A few things that come to mind:

1. Missing `vendor` directory
2. Missing `third_party` directory
3. Missing `hack` directory with `update-codegen.sh` and `update-deps.sh` to generate the above

It's a bit unclear why we need the Mage stuff in here, that we have nowhere else. Any insights into that?

**Comment by cardil** [comment]
This repo was intentionally done by me in different share than any other knative repo. I wanted it to act as a showcase of how knative can move out of this **awful** setup you just have described above. That was my second goal, apart from doing kn-event plugin. To hit two birds with one stone.

Nevertheless, I think we should align this repo with other knative repos, to enable work of others on it. I have a source repo [cardil/kn-event](https://github.com/cardil/kn-event) still, that I can use to showcase that different project setup. We spoke about that already with @rhuss.

**Comment by markusthoemmes** [comment]
Sounds reasonable. It'd be nice to document what you find awful in the current setup so painpoints can be tackled in a targeted way.

**Comment by cardil** [comment]
Sure. I'm thinking of doing a slides about that.

**Comment by cardil** [comment]
Does #15 fix this? 

It still isn't 100% consistent as presubmit is doing nothing, and this repo has tighter golangci-lint roles enabled.

**Comment by rhuss** [comment]
I thinks this is good enough (thanks @markusthoemmes !), so let's close this and continue on-demand to set up the CI.
