### ISSUE TITLE
Plugin attempts to list brokers at cluster scope

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/kn-plugin-event#185]
**Describe the bug**
Trying to send an event to a broker in a particular namespace `somens` fails due to restricted permissions 

For example
```
kn event send \
    --type dev.knative.sources.ping \
    --id $(uuidgen) \
    --field somekey=someValue \
    --to Broker:eventing.knative.dev/v1:default -n somens
```
fails with 
```
Error: can't sent event: reference is invalid: resource isn't addressable: failed to get lister for eventing.knative.dev/v1, Resource=brokers: brokers.eventing.knative.dev is forbidden: User "system:serviceaccount:somens:knative-developer-sa" cannot list resource "brokers" in API group "eventing.knative.dev" at the cluster scope
```
As I dont have permissions to list brokers at cluster scope, but I do at the namespace scope.

 **Expected behavior**
Able to send a event successfully

 **To Reproduce**
- Create a service account which doesn't have permissions to list brokers at cluster scope and attempt to send an event to a broker.

 **Knative release version**
v1.2

 **Additional context**

**Comment by cardil** [comment]
Thanks for sending this issue. Let me clarify the kn-event behavior, so we'll be on the same page.

The kn-event will try to send the event by creating a job within a namespace of the target. The target's namespace is specified using `--namespace`, `-n` option.

You could override this behavior, by using the `--sender-namespace` option.

Please, try sending your event with:

```bash
kn event send \
    --type dev.knative.sources.ping \
    --id $(uuidgen) \
    --field somekey=someValue \
    --to Broker:eventing.knative.dev/v1:default \
    --namespace somens \
    --sender-namespace default # use namespace where you have permissions to create/delete jobs
```

At this point, I don't see this as an issue of kn-event. How do you think the kn-event should operate, if you don't have sufficient permissions on the cluster? Maybe you will be satisfied with a more intuitive error message?

**Comment by cardil** [comment]
Closing.

@xtreme-sameer-vohra If you consider this a bug of kn-event, please answer my questions above, and reopen the issue.
